---
- name: "local facts using static value and python for dynamic value"
  hosts: localhost
  connection: local

  tasks:

   - name: "Create fact directory"
     file:
       path: "/etc/ansible/facts.d/"
       recurse: yes
       state: "directory"

   - name: "Create a static custom fact foo"
     copy:
       content: '"bar"'
       dest: /etc/ansible/facts.d/foo.fact

   - name: Create a dynamic custom fact foobar
     copy:
       dest: /etc/ansible/facts.d/foobar.fact
       mode: 0775
       content: |
         #!/usr/bin/python3
         import json
         def render_data(data):
            return json.dumps(data)
         arbitrary_data = {}
         arbitrary_data["foobar"] = []
         arbitrary_data["foobar"].append("foo")
         if True:
            arbitrary_data["foobar"].append("bar")
         print(render_data(arbitrary_data["foobar"]))

   - name: "Re-run setup to use custom facts"
     setup: ~
 
   - name: "debug var"
     debug:
       var: ansible_local

#   - name: "Print all available facts"
#     ansible.builtin.debug:
#       var: ansible_facts
