---
- name: "local facts with shell script"
  hosts: localhost
  connection: local
#  become: true
#  gather_facts: true
 

  tasks:
  - name: "Ensure custom fact directory exists"
    file:
      path: "/etc/ansible/facts.d"
      recurse: yes
      state: "directory"
 
  - name: "Load custom parse files fact"
    copy:
      src: '{{ playbook_dir }}/facts/file-parse-fact.fact'
      dest: /etc/ansible/facts.d/file-parse-fact.fact
      mode: 0755

  - name: "Load custom json fact"
    copy:
      src: '{{ playbook_dir }}/facts/json-fact.fact'
      dest: /etc/ansible/facts.d/json-fact.fact
      mode: 0755
 
  - name: "Re-run setup to use custom facts"
    setup: ~
 
  - name: "debug var"
    debug:
      var: ansible_local

#  - name: "Print all available facts"
#    ansible.builtin.debug:
#      var: ansible_facts
