---
- name: "local facts using static value and python for dynamic value"
  hosts: localhost
  connection: local

  tasks:

   - name: "Create fact directory"
     file:
       path: "/etc/ansible/facts.d/"
       recurse: yes
       state: "directory"

   - name: "Create a static custom fact foo"
     copy:
       content: '"bar"'
       dest: /etc/ansible/facts.d/foo.fact

   - name: "Create a dynamic custom fact using api call"
     copy:
       dest: /etc/ansible/facts.d/api-call.fact
       mode: 0775
       content: |
         #!/bin/bash
         curl https://www.googleapis.com/auth/userinfo.email

   - name: "debug var"
     debug: var=ansible_local

#   - name: "Print all available facts"
#     ansible.builtin.debug:
#       var: ansible_facts
