---
- name: "local facts using static value and bash for dynamic value"
  hosts: localhost
  connection: local

  tasks:

   - name: "Create fact directory"
     file:
       path: "/etc/ansible/facts.d/"
       recurse: yes
       state: "directory"

   - name: "Create a static custom fact foo"
     copy:
       content: '"bar"'
       dest: /etc/ansible/facts.d/foo.fact

   - name: "Insert custom fact file active cards"
     copy:
       src: '{{ playbook_dir }}/facts/api-fact.fact'
       dest: /etc/ansible/facts.d/api-fact.fact
       mode: 0755

   - name: "Re-run setup to use custom facts"
     setup: ~

   - name: "debug var"
     debug: var=ansible_local

#   - name: "Print all available facts"
#     ansible.builtin.debug:
#       var: ansible_facts
