---
- hosts: all
  tasks:
    - name: Create variable from command
      shell: cat /etc/hello.txt
      register: command_output
    - name: Set var for subsequent job templates
      set_stats:
        data:
          P1: "{{ command_output }}"
