---
- hosts: all
  tasks:
    - name: Create variable from command
      shell: echo "New Task, Who Dis?"
      register: command_output
    - name: Set var for subsequent job templates
      set_stats:
        data:
          P1: "{{ command_output }}"
