---
- hosts: all
  tasks:
  - name: Set the variable
    set_fact:
      greeting: "{{ 'Hello ' + P1.stdout|default('Everyone') + '!' }}"
  - name: Give the people what they want
    shell: cat /etc/hello.cow
    register: command_output
  - name: Set full greeting
    set_fact:
      full_greeting: "{{ greeting }} {{ command_output.stdout_lines }}"
  - debug: msg="{{ full_greeting }}"

