---
- name: "show me the local facts"
  hosts: localhost
  connection: local

  tasks:
  - name: "Ensure custom fact directory exists"
    file:
      path: "/etc/ansible/facts.d"
      recurse: yes
      state: "directory"

  - name: "Re-run setup to use custom facts"
    setup: ~

  - name: "debug var"
    debug:
      var: ansible_local
