---
- name: Executing Terraform
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
  - name: plan
    debugger: always
    terraform:
      project_path: '{{ playbook_dir }}/tf/'
      lock: true
      force_init: yes
    register: tf_plan_output
    
  - name: Print plan outputs
    debug:
      var: tf_plan_output
    
  - name: apply
    debugger: always
    terraform:
      project_path: '{{ playbook_dir }}/tf/'
      lock: true
      state: present
    register: tf_apply_output
      
  - name: Print apply outputs
    debug:
      var: tf_apply_output
